### ISSUE TITLE
callback in signal_connect doesn't return widget

### ISSUE THREAD

**Issue by lobingera** [JuliaLang/Gtk.jl#175]
Following the Gtk documentation e.g. https://developer.gnome.org/gtk-tutorial/stable/x159.html
> The function specified in the third argument is called a "callback function", and should generally be of the form

> void callback_func( GtkWidget *widget,
>                     ... /* other signal arguments */
>                     gpointer   callback_data );

> where the first argument will be a pointer to the widget that emitted the signal, and the last a pointer to the data given as the last argument to the g_signal_connect() function as shown above.

The callbacks assigned by the Gtk.jl (via cfunction etc.) does -somehow- not provide the widget as first entry. 
https://gist.github.com/1a5e103c4ff56f191dce shows an example function that reports the entries of the draw function on screen, everytime the widget needs redrawing.

Getting the widget into the callback is done here by relaying with the callback_data.

**Comment by vtjnash** [comment]
This is because that documentation is for the C interface, but that doesn't quite match what the Julia-C connector requires. There is documentation, but is is lacking in details on the expected transformation https://github.com/JuliaLang/Gtk.jl/blob/master/doc/more_signals.md.

Given a signature of the form
`rettype callback_func( GtkWidget widget, /* other signal arguments, */ gpointer callback_data );`
from the Gtk C documentation, the standard conversion is to either use the simple interface (by not specifying any types when creating the callback):
`callback_func(widget, other_signal_args...)`

Or use the "bare metal" interface:
`callback_func(::Ptr{Void}, other_signal_args..., user_data)`
Where `user_data` defaults to being the widget, unless otherwise specified by the user when creating the callback.

This means that the first and last argument are usually dropped when creating a description of the type signature.

**Comment by lobingera** [comment]
I can't fully follow. So there is a technical reason that the widget isn't returned at the first Position? What is actually in the first Position?

**Comment by timholy** [comment]
In the "bare metal" interface, the first argument is a pointer to a `GtkWidget`. You can convert it to the actual widget with `widget = convert(Button, widgetp)` as demonstrated in the [example](https://github.com/JuliaLang/Gtk.jl/blob/master/doc/more_signals.md).

In the `signal_connect` call, you omit the first and last argument in the `parameter_type_tuple`, because those are handled automatically.
